services:
  frontend:
    build:
      context: .
      network: host
    container_name: frontend_vue
    ports:
      - "5174:5174"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend-net
    environment:
      - CHOKIDAR_USEPOLLING=true # Ayuda con el hot reload en algunos sistemas locales

networks:
  backend-net:
    external: true
    name: backend_eventos_laravel_laravel-net
